executable              = execution2.sh
arguments               = $(ClusterId)$(ProcId)
output                  = out/job2.$(ClusterId).$(ProcId).out
error                   = err/job2.$(ClusterId).$(ProcId).err
log                     = log/job2.$(ClusterId).log
should_transfer_files   = YES
transfer_input_files    = ./part2.py, ./stratified_mc.py,  ./parameters.py
when_to_transfer_output = ON_EXIT
+JobFlavour = "tomorrow"
request_GPUs = 1
request_CPUs = 4
queue
