executable              = execution3.sh
arguments               = $(ClusterId)$(ProcId)
output                  = out/job3.$(ClusterId).$(ProcId).out
error                   = err/job3.$(ClusterId).$(ProcId).err
log                     = log/job3.$(ClusterId).log
should_transfer_files   = YES
transfer_input_files    = ./part3.py, ./stratified_mc.py,  ./parameters.py  
when_to_transfer_output = ON_EXIT
+JobFlavour = "tomorrow"
request_GPUs = 1
request_CPUs = 1
queue
