executable              = generate_radial_scan.sh
arguments               = $(ClusterId)$(ProcId)
output                  = out/job_generate.$(ClusterId).$(ProcId).out
error                   = err/job_generate.$(ClusterId).$(ProcId).err
log                     = log/job_generate.$(ClusterId).log
should_transfer_files   = YES
transfer_input_files    = ./generate_radial_scan.py
when_to_transfer_output = ON_EXIT
+JobFlavour = "tomorrow"
request_GPUs = 1
request_CPUs = 1
queue
